/**
 * E65
 * Copyright (C) 2018 David Jolly
 *
 * E65 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * E65 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef E65_TEST_FUNCTIONAL_PROCESSOR_TYPE_H_
#define E65_TEST_FUNCTIONAL_PROCESSOR_TYPE_H_

#include "../../../include/type/exception.h"

namespace e65 {

	namespace test {

		namespace functional {

			#define E65_TEST_FUNCTIONAL_PROCESSOR_HEADER "[E65::TEST::FUNCTIONAL::PROCESSOR]"
#ifndef NDEBUG
			#define E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_HEADER E65_TEST_FUNCTIONAL_PROCESSOR_HEADER " "
#else
			#define E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_HEADER
#endif // NDEBUG

			enum {
				E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_NONE = 0,
			};

			#define E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_MAX E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_NONE

			static const std::string E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_STR[] = {
				E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_HEADER "",
				};

			#define E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_STRING(_TYPE_) \
				(((_TYPE_) > E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_MAX) ? E65_STRING_UNKNOWN : \
					E65_STRING_CHECK(E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_STR[_TYPE_]))

			#define THROW_E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION(_EXCEPT_) \
				THROW_E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_FOMAT(_EXCEPT_, "", "")
			#define THROW_E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_FOMAT(_EXCEPT_, _FORMAT_, ...) \
				E65_EXCEPTION_THROW_FORMAT(E65_TEST_FUNCTIONAL_PROCESSOR_EXCEPTION_STRING(_EXCEPT_), _FORMAT_, __VA_ARGS__)

			#define E65_TEST_FUNCTIONAL_PROCESSOR_ACCUMULATOR_VALUE 0x00
			#define E65_TEST_FUNCTIONAL_PROCESSOR_CYCLE_VALUE 7
			#define E65_TEST_FUNCTIONAL_PROCESSOR_CYCLE_LAST_VALUE 0
			#define E65_TEST_FUNCTIONAL_PROCESSOR_FLAGS_VALUE \
				(E65_PFLAG(e65::type::E65_PFLAG_BREAKPOINT) | E65_PFLAG(e65::type::E65_PFLAG_IRQ_DISABLE) \
					| E65_PFLAG(e65::type::E65_PFLAG_UNUSED))
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INDEX_X_VALUE 0x00
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INDEX_Y_VALUE 0x00
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INTERRUPT_MASKABLE false
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INTERRUPT_MASKABLE_ADDRESS 0xfffe
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INTERRUPT_NON_MASKABLE false
			#define E65_TEST_FUNCTIONAL_PROCESSOR_INTERRUPT_NON_MASKABLE_ADDRESS 0xfffa
			#define E65_TEST_FUNCTIONAL_PROCESSOR_RESET_ADDRESS 0xfffc
			#define E65_TEST_FUNCTIONAL_PROCESSOR_STACK_POINTER_VALUE 0xfd
			#define E65_TEST_FUNCTIONAL_PROCESSOR_START_ADDRESS 0x0600
			#define E65_TEST_FUNCTIONAL_PROCESSOR_STOP_VALUE false
			#define E65_TEST_FUNCTIONAL_PROCESSOR_WAIT_VALUE false

			enum {
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_CLC_IMPLIED = 0,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_CLD_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_CLI_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_CLV_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_NOP_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_SEC_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_SED_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_SEI_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_STP_IMPLIED,
				E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_WAI_IMPLIED,
			};

			#define E65_TEST_FUNCTIONAL_PROCESSOR_MAX E65_TEST_FUNCTIONAL_PROCESSOR_COMMAND_WAI_IMPLIED

			static const std::string E65_TEST_FUNCTIONAL_PROCESSOR_STR[] = {
				"Command-Clc-Implied",
				"Command-Cld-Implied",
				"Command-Cli-Implied",
				"Command-Clv-Implied",
				"Command-Nop-Implied",
				"Command-Sec-Implied",
				"Command-Sed-Implied",
				"Command-Sei-Implied",
				"Command-Stp-Implied",
				"Command-Wai-Implied",
				};

			#define E65_TEST_FUNCTIONAL_PROCESSOR_STRING(_TYPE_) \
				(((_TYPE_) > E65_TEST_FUNCTIONAL_PROCESSOR_MAX) ? E65_STRING_UNKNOWN : \
					E65_STRING_CHECK(E65_TEST_FUNCTIONAL_PROCESSOR_STR[_TYPE_]))
		}
	}
}

#endif // E65_TEST_FUNCTIONAL_PROCESSOR_TYPE_H_
